version: '3.8'

services:
  app:
    build: .
    container_name: vbb-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongodb:27017/vbb_db  # Optional: specify database name

  mongodb:
    image: mongo:6
    container_name: mongo-vbb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
volumes:
  mongo_data:
